//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using tpC;

class Model : DbContext
{
    public Model() : base("employe")
    {

    }

    public DbSet<Employee> employees { get; set; }
    public DbSet<Departement> departements { get; set; }
}