//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDbStaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_MFI
    {
        public int MFI_ID { get; set; }
        public int SECTOR_ID { get; set; }
        public Nullable<decimal> NUMBER_OF_REGISTERED_CLIENTS_YTD { get; set; }
        public Nullable<decimal> NUMBER_OF_CLIENTS_WITH_LOANS { get; set; }
        public Nullable<double> MALE_CLIENTS_YTD { get; set; }
        public Nullable<double> FEMALE_CLIENTS_YTD { get; set; }
        public Nullable<double> MALE_CLIENTS_35 { get; set; }
        public Nullable<double> FEMALE_CLIENTS_35 { get; set; }
        public Nullable<decimal> NB_BRANCH_RURAL { get; set; }
        public Nullable<decimal> NB_BRANCH_URBAN { get; set; }
        public Nullable<double> GROSS_OUTSTANDING_PORTFOLIO { get; set; }
        public Nullable<double> OUTSTANDING_LOAN_GENDER_MALE { get; set; }
        public Nullable<double> OUTSTANDING_LOAN_GENDER_FEMALE { get; set; }
        public Nullable<double> TOTAL_LOAN_DISBURSED { get; set; }
        public Nullable<double> LOAN_DISBURSED_WOMEN { get; set; }
        public Nullable<double> LOAN_DISBURSED_MEN { get; set; }
        public Nullable<double> CURRENT_MFI { get; set; }
        public Nullable<double> OVERDUE_1_30 { get; set; }
        public Nullable<double> OVERDUE_31_60 { get; set; }
        public Nullable<double> OVERDUE_61_90 { get; set; }
        public Nullable<double> OVERDUE_91_180 { get; set; }
        public Nullable<double> OVERDUE_181_365 { get; set; }
        public Nullable<double> OVERDUE_365 { get; set; }
        public Nullable<double> CURRENT_PAR_0 { get; set; }
        public Nullable<double> PAR_1_30_DAYS { get; set; }
        public Nullable<double> PAR_31_60_DAYS { get; set; }
        public Nullable<double> PAR_61_90 { get; set; }
        public Nullable<double> PAR_91_180 { get; set; }
        public Nullable<double> PAR_181_365 { get; set; }
        public Nullable<double> PAR_365 { get; set; }
        public Nullable<decimal> NO_OF_LOANS_SECTOR { get; set; }
        public Nullable<double> OUTSTANDING_LOAN_SECTOR { get; set; }
        public Nullable<double> PAR_30_SECTOR_AMT { get; set; }
        public Nullable<decimal> NO_OF_LOANS_PURPOSE { get; set; }
        public Nullable<decimal> OUTSTANDING_LOAN_PURPOSE { get; set; }
        public Nullable<double> PAR_30_PURPOSE_AMT { get; set; }
        public int PURPOSE_ID { get; set; }
        public int AGING_ID { get; set; }
        public int DATE_ID { get; set; }
        public int TK_ID { get; set; }
        public int MONTH_ID { get; set; }
        public int YEAR_ID { get; set; }
        public int QUARTER_ID { get; set; }
        public int WEEK_ID { get; set; }
        public int fact_id { get; set; }
    
        public virtual AGING AGING { get; set; }
        public virtual MFI_DETAILS MFI_DETAILS { get; set; }
        public virtual PURPOSE PURPOSE { get; set; }
        public virtual SECTOR SECTOR { get; set; }
    }
}
