//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDbStaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFI_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MFI_DETAILS()
        {
            this.FACT_MFI = new HashSet<FACT_MFI>();
        }
    
        public int MFI_id { get; set; }
        public string MFI_NAME { get; set; }
        public Nullable<double> Year_of_incorporation { get; set; }
        public Nullable<double> members_of_the_board { get; set; }
        public Nullable<double> Number_of_staff { get; set; }
        public Nullable<double> Number_of_loan_officers { get; set; }
        public string MIS { get; set; }
        public string Mission_statement { get; set; }
        public string Vision_statement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACT_MFI> FACT_MFI { get; set; }
    }
}
