//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDbStaging.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGING> AGINGs { get; set; }
        public virtual DbSet<FACT_MFI> FACT_MFI { get; set; }
        public virtual DbSet<MFI_DETAILS> MFI_DETAILS { get; set; }
        public virtual DbSet<PURPOSE> PURPOSEs { get; set; }
        public virtual DbSet<SECTOR> SECTORs { get; set; }
    
        public virtual ObjectResult<CLIENT_SEXE_BY_MFI_Result> CLIENT_SEXE_BY_MFI(Nullable<int> mfiid)
        {
            var mfiidParameter = mfiid.HasValue ?
                new ObjectParameter("mfiid", mfiid) :
                new ObjectParameter("mfiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLIENT_SEXE_BY_MFI_Result>("CLIENT_SEXE_BY_MFI", mfiidParameter);
        }
    
        public virtual ObjectResult<RURAL_URBAN_BY_MFI_Result> RURAL_URBAN_BY_MFI(Nullable<int> mfiid)
        {
            var mfiidParameter = mfiid.HasValue ?
                new ObjectParameter("mfiid", mfiid) :
                new ObjectParameter("mfiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RURAL_URBAN_BY_MFI_Result>("RURAL_URBAN_BY_MFI", mfiidParameter);
        }
    }
}
