//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.CardValidatorwssoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="CardValidatorwssoap.CreditCardWS")]
    public interface CreditCardWS {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/CreditCardWS/validateRequest", ReplyAction="http://ws/CreditCardWS/validateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.CardValidatorwssoap.validateResponse validate(ConsoleApplication1.CardValidatorwssoap.validateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/CreditCardWS/validateRequest", ReplyAction="http://ws/CreditCardWS/validateResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.CardValidatorwssoap.validateResponse> validateAsync(ConsoleApplication1.CardValidatorwssoap.validateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class creditCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cnField;
        
        private string expiryDateField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string numberField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cn {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
                this.RaisePropertyChanged("cn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validate", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class validateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.CardValidatorwssoap.creditCard entity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public validateRequest() {
        }
        
        public validateRequest(ConsoleApplication1.CardValidatorwssoap.creditCard entity, string token) {
            this.entity = entity;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class validateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validateResponse() {
        }
        
        public validateResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditCardWSChannel : ConsoleApplication1.CardValidatorwssoap.CreditCardWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardWSClient : System.ServiceModel.ClientBase<ConsoleApplication1.CardValidatorwssoap.CreditCardWS>, ConsoleApplication1.CardValidatorwssoap.CreditCardWS {
        
        public CreditCardWSClient() {
        }
        
        public CreditCardWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.CardValidatorwssoap.validateResponse ConsoleApplication1.CardValidatorwssoap.CreditCardWS.validate(ConsoleApplication1.CardValidatorwssoap.validateRequest request) {
            return base.Channel.validate(request);
        }
        
        public bool validate(ConsoleApplication1.CardValidatorwssoap.creditCard entity, string token) {
            ConsoleApplication1.CardValidatorwssoap.validateRequest inValue = new ConsoleApplication1.CardValidatorwssoap.validateRequest();
            inValue.entity = entity;
            inValue.token = token;
            ConsoleApplication1.CardValidatorwssoap.validateResponse retVal = ((ConsoleApplication1.CardValidatorwssoap.CreditCardWS)(this)).validate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.CardValidatorwssoap.validateResponse> ConsoleApplication1.CardValidatorwssoap.CreditCardWS.validateAsync(ConsoleApplication1.CardValidatorwssoap.validateRequest request) {
            return base.Channel.validateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.CardValidatorwssoap.validateResponse> validateAsync(ConsoleApplication1.CardValidatorwssoap.creditCard entity, string token) {
            ConsoleApplication1.CardValidatorwssoap.validateRequest inValue = new ConsoleApplication1.CardValidatorwssoap.validateRequest();
            inValue.entity = entity;
            inValue.token = token;
            return ((ConsoleApplication1.CardValidatorwssoap.CreditCardWS)(this)).validateAsync(inValue);
        }
    }
}
