//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbFirst_autoecole
{
    using System;
    using System.Collections.Generic;
    
    public partial class LECON
    {
        public int numero { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<short> codeEleve { get; set; }
        public Nullable<short> heure { get; set; }
        public Nullable<short> duree { get; set; }
        public bool effectuee { get; set; }
        public string numImmaVehicule { get; set; }
    
        public virtual ELEVE ELEVE { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
