//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ouvrage
    {
        public int ID { get; set; }
        public string Titre { get; set; }
        public Nullable<int> ID_Auteur { get; set; }
    
        public virtual auteur auteur { get; set; }
    }
}
