//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpH
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACATAIRE : PROFESSEUR
    {
        public int nbreHeure { get; set; }
        public decimal tauxHoraire { get; set; }
    }
}
